In [1]:
import numpy as np

In [2]:
a = [5]
b = [1 ,2 , 3]
c = [[1,2,3],[4,5,6],[7,8,9]]

In [3]:
#list ---> Array Vector
vector = np.array(b)

In [4]:
vector

array([1, 2, 3])

In [5]:
#convert list of list to metrics
matrics = np.array(c)

In [6]:
matrics

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#create a array in range like lists
x = np.arange(0,10)

In [8]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#Ones metrics
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#for identity matrics
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Method

In [21]:
np.random.rand(4)

array([0.58338359, 0.35877725, 0.67199727, 0.80264594])

In [22]:
np.random.rand(4,5)

array([[0.00573159, 0.58693535, 0.1864256 , 0.2276766 , 0.5318178 ],
       [0.22945723, 0.8123338 , 0.28671544, 0.68779282, 0.45007285],
       [0.23437945, 0.54381831, 0.61456958, 0.647892  , 0.49064843],
       [0.48391895, 0.37102185, 0.65020593, 0.84843098, 0.97872055]])

In [23]:
 np.random.randn(3)

array([ 0.96946314, -0.67227641,  0.95345403])

In [24]:
np.random.randint(20,100)

49

In [25]:
np.random.randint(10,100,15)

array([84, 91, 88, 94, 21, 48, 65, 97, 41, 81, 42, 10, 87, 58, 91])

In [26]:
random_arr = np.random.randint(0,50,10)

In [27]:
random_arr

array([19, 49, 49,  3, 10, 38, 40, 19, 24, 35])

In [28]:
# 1D ---> 2D
random_arr.reshape(2,5)

array([[19, 49, 49,  3, 10],
       [38, 40, 19, 24, 35]])

In [29]:
#for max number
random_arr.max()

49

In [30]:
#for min number
random_arr.min()

3

In [31]:
#give index
random_arr.argmax()

1

In [32]:
#give index
random_arr.argmin()

3

In [33]:
#shape check of array
random_arr.shape

(10,)

In [34]:
from numpy.random import randint 

In [35]:
randint(6,17)

10

In [43]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [46]:
ones_arr = np.ones((2, 3))
zeros_arr = np.zeros((2, 3))

concatenated_arr = np.concatenate((ones_arr, zeros_arr), axis=0)
print(concatenated_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 1D Array

In [73]:
arr_1D = np.arange(1,11)

In [59]:
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr_1D[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr_1D[5:]

array([ 6,  7,  8,  9, 10])

In [62]:
#broadcasting 
arr_1D[7:] = 20

In [63]:
arr_1D

array([ 1,  2,  3,  4,  5,  6,  7, 20, 20, 20])

In [70]:
arr_1D[::-1]

array([20, 20, 20,  7,  6,  5,  4,  3,  2,  1])

In [72]:
arr_1D[2::-1]

array([3, 2, 1])

In [74]:
arr_1D_COPY = arr_1D.copy()

In [75]:
arr_1D_COPY

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 2D Array

In [36]:
array2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [37]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
#Slicing   ----->>> Index start from 0 that's why 2 mean 3rd row 3rd column
array2d[2][2]

9

In [40]:
array2d[1]

array([4, 5, 6])

In [41]:
array2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [42]:
array2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr1 = np.arange(1,10)

In [48]:

arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
#boolean array
cond_arr = arr1>5

In [50]:
cond_arr

array([False, False, False, False, False,  True,  True,  True,  True])

In [52]:
arr1[cond_arr]

array([6, 7, 8, 9])

In [53]:
arr_2d = np.arange(50).reshape(5,10)

In [54]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [55]:
arr_2d[3:5,3:]

array([[33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49]])

## Numpy Operation

In [76]:
arr3 = np.arange(1,11)

In [77]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
print(np.sum(arr3))   
print(np.mean(arr3)) # mean
print(np.median(arr3)) # median
print(np.std(arr3)) # Standard deviation
print(np.min(arr3)) # Minimum Number
print(np.max(arr3))  # Maximum Number

55
5.5
5.5
2.8722813232690143
1
10


In [79]:
arr3_add = arr3 + arr3

In [80]:
arr3_add

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
subtract = arr3 - arr3

In [82]:
subtract

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [83]:
scalar = arr3 *100

In [84]:
scalar

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [85]:
multiply = arr3 *arr3

In [86]:
multiply

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [90]:
arr4 = np.array([[5,6,7],[0,9,8]])

In [91]:
transpose_arr = np.transpose(arr4)

In [92]:
transpose_arr

array([[5, 0],
       [6, 9],
       [7, 8]])

In [93]:
dot_product = np.dot(transpose_arr, arr4)
print(dot_product)

[[ 25  30  35]
 [ 30 117 114]
 [ 35 114 113]]


In [94]:
#Exponential function
exp_arr = np.exp(arr4)

In [95]:
exp_arr

array([[1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [1.00000000e+00, 8.10308393e+03, 2.98095799e+03]])

In [96]:
arr_to_sort = np.array([3, 1, 4, 2, 5])
sorted_arr = np.sort(arr_to_sort)

In [97]:
sorted_arr

array([1, 2, 3, 4, 5])

In [98]:
# Statistical Functions
hist, bin_edges = np.histogram(arr_to_sort, bins=[0, 2, 4, 6])
print(hist)
print(bin_edges)

[1 2 2]
[0 2 4 6]


In [100]:
# Correlation Coefficient
data = np.array([10, 20, 30, 40, 50])
data2 = np.array([20, 30, 40, 50, 60])
correlation_coefficient = np.corrcoef(data, data2)[0, 1]
print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 1.0


In [101]:
# Covariance Matrix
cov_matrix = np.cov(data, data2)
print("Covariance Matrix:", cov_matrix)

Covariance Matrix: [[250. 250.]
 [250. 250.]]


In [102]:
log_arr = np.log(arr3)

In [103]:
log_arr

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [104]:
sin_arr = np.sin(arr3)
sin_arr

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [105]:
tan_arr = np.tan(arr3)

In [106]:
tan_arr

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])